---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-serviceaccount
  namespace: default
imagePullSecrets:
  - name: myregistrykey
---
apiVersion: v1
kind: Secret
metadata:
  name: sample-serviceaccount-token
  annotations:
    kubernetes.io/service-account.name: sample-serviceaccount
type: kubernetes.io/service-account-token
---

