apiVersion: v1
kind: Pod
metadata:
  name: samle-fsgroup
spec:
  securityContext:
    fsGroup: 1001
  containers:
    - image: nginx:1.16
      name: nginx-container
      volumeMounts:
        - mountPath: /cache
          name: cache-volume
  volumes:
    - name: cache-volume
      emptyDir: {}
