apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databases.stable.example.com
spec:
  group: stable.example.com
  scope: Namespaced
  names:
    plural: databases
    singular: database
    kind: Database
    shortNames:
      - hbd
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                dbType:
                  type: string
                  pattern: "^(mysql|mariadb|postgresql)$"
                  default: mysql
                diskSize:
                  type: integer
                  minimum: 10
                  maximum: 1000
                  default: 20
      additionalPrinterColumns:
        - name: Type
          type: string
          description: Database type (mysql|mariadb|postgresql)
          jsonPath: .spec.dbType
        - name: DiskSize
          type: integer
          description: Database disk size
          jsonPath: .spec.diskSize
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
