apiVersion: v1
kind: Pod
metadata:
  name: sample-secret-single-volume
spec:
  containers:
    - name: secret-container
      image: nginx:1.16
      volumeMounts:
        - name: config-name
          mountPath: /config
  volumes:
    - name: config-name
      secret:
        secretName: sample-db-auth
        items:
          - key: username
            path: username.txt
