apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: sample-podsecuritypolicy
spec:
  privileged: false
  runAsUser:
    rule: RunAsAny
  alloPrivilegedEscalation: true
  allowedCapabilities:
    - '*'
  allowedHostPaths:
    - pathPrefix: "/etc"
  fsGroup:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  volumes:
    - '*'