apiVersion: v1
kind: Pod
metadata:
  name: sample-tolerations-second
spec:
  containers:
    - name: ngix-container
      image: nginx:1.16
  tolerations:
    - key: "env"
      operator: "Equal"
      value: "prd"
      effect: "NoExecute"
      tolerationSeconds: 45
