---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sample-db-auth
  namespace: default
spec:
  encryptedData:
    password: AgAMZebSlZkHH7Jk2dWBykh+sxY/886QC8p2/iPwv7aVmBZhw0iLkgGCjBFjnzXCNEjA9Lxf7QTnM0OlvQbke/3mKjg8wBQeckNXm/YF9cJkAwnP+aYt6f6++wATRAyHs9bGV/gaCeCzco53yGkbEcTT21ONunR43HXOa5Qx8I0Wvwy/1dl9mEg0xwqry+TSHuvq46coEXvVgPQI6o0AfCg5N1SYa59icvH+aGbw0ooUjkKTT5ESjtcB0hPScoJDFPl8rALSrKsaQmfJXNz3iglomaGDj0TOMrLQkGdDNhqzvH+M2h21mRWZDsG6nfk1xdhkhnCtxWJpNyRRXKJH8XxmypJGABCS2UrrfFwuJPgBUBoUrKQrS2EaZkclJJ6sTu85cbTnZ0lc+DDoAtTYMgeoOVxr4wOidmZUhtffJ5XUKAHBw0izhfDRinn+P/JVhJkUKRymQIQjvAE8KLbZ9XnjK1cIv31ffgDXrU+fatGUifWeAQUO8icmFCjTqP8iw0E5vVCyGuUjuBh35GP6EDWPT1UuuPmcKm5DDyY58QadxKfD5hCLg5GCW36N2dynPdDAWLEkq5GuSSm6QBgL9u2cw5/zzOCRQuu64YhI+fX28jOtvckdOKgLjt1ap7DgEuo7g8neKb865bMgmBMh0KBV6hm7EUO6YdbN+BNO5pQGLomQWQc+KcQtuzYHRRm9/iA39kr22lRC5n3cUj8=
    username: AgCxuWGKp+gq8GXzOwaTzcmgVklTXUY62G7+/7OHEhdZ0Qzoii9HlK4zFBgUNmlX7uL9nmgcOtHFwmKVtRm6TzEK0C0QbhIFPotQrWZUoZ4HPbW6Ko9YVJ1pURvoGEvz3lp1CKRPRTu1xOR0ejGdL/aCwKta44A3lCgbsLkCKiRq9Xjsym3owW2/5lBN68B93eEZzIW4UdRKPOLDjJLzj8AStWg3bgKftTuejEhwH15yJNnE1bXNne807mhixI9Cx4Vzhk0Tl+h1+HIRynjpi+9SPOhXUNkc8bDV1AIiQ1CPKiVc+Z0MteazVx6qXm0pZk7CWcCcxsX7PmviEaEqy5E8zmCA/La+c8smFpzVWoPO+e5pUrTIh3PeRPAarpUDL9U71pYLkHhLPy4mpNmu/zOieIljO0/M3tjtmD3M2P6jVfGodlTK4CScDlHwKwVBj6wLC/Gmcv0aLQZuaw9oohiB+SbqqNyLQ3nOsfdMnWedB/X97SVDqf/vkf5/PLyhjeNdhzgVDaKDJWkZk+jDXEDESAsGSd5KEq1dCZiwVNSVfJBQyvvMze/JYKSVlVPrwf5CKlvikSzOh1plcWNfSnPGkJZjPs0Dmsy657Hfp4PMHUX4c1CshdhgUhH2Y9MsH4F7v2vnrtKS30e8YBLU7N6u9ilN05Fmevk91ThLWeVdu4Uo3wmAkU33UQbW0TooKW5D5CDb
  template:
    metadata:
      name: sample-db-auth
      namespace: default
    type: Opaque
