apiVersion: skaffold/v2alpha3
kind: Config
build:
  artifacts:
    - image: dockerhub_user/sample-skaffold
      docker:
        dockerfile: ./Dockerfile
  tagPolicy:
    dateTime: {}
  local:
    push: false
deploy:
  kubectl:
    manifests:
      - skaffold-*
